// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7WxIF3MlUPKrLrQwpR0-pyXAVIQNyvns',
    appId: '1:468889420149:web:7085d17561389c5c0b133c',
    messagingSenderId: '468889420149',
    projectId: 'taskly-2026',
    authDomain: 'taskly-2026.firebaseapp.com',
    storageBucket: 'taskly-2026.firebasestorage.app',
    measurementId: 'G-P157LCS93N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeci4g4eO_tXi2uxtYdWhJTvPSVHmLlEo',
    appId: '1:468889420149:android:e2a4a53ca034d7f90b133c',
    messagingSenderId: '468889420149',
    projectId: 'taskly-2026',
    storageBucket: 'taskly-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPlLhGUV40mYJqlRrs6JYl-1vebna8hyk',
    appId: '1:468889420149:ios:38c1b7cffeb934120b133c',
    messagingSenderId: '468889420149',
    projectId: 'taskly-2026',
    storageBucket: 'taskly-2026.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );
}
